# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cirrus < Formula
  desc ""
  homepage ""
  version "1.0.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v1.0.0/cirrus-darwin-amd64.tar.gz"
      sha256 "4b88adb3160598ff7c7c91dd51763ed053e7d29feba5b7e066349dabfffa9bfc"

      define_method(:install) do
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v1.0.0/cirrus-darwin-arm64.tar.gz"
      sha256 "cf2b56e7afcf0cd0999acf08fc7ce8c0e8dbf5e641eadf9fafb22e9e0af95efb"

      define_method(:install) do
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v1.0.0/cirrus-linux-amd64.tar.gz"
      sha256 "a2aed881d8d0bfb17466a1bdfaaa553ca3ae64ea0bef57aa1a47107322941933"
      define_method(:install) do
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v1.0.0/cirrus-linux-arm.tar.gz"
      sha256 "d635c75ef3a524a7e205cc7eb601d2fc88526a1f480fac57fa8d5b8c86117e27"
      define_method(:install) do
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/cirrus-cli/releases/download/v1.0.0/cirrus-linux-arm64.tar.gz"
      sha256 "801aa5a6ee757a5872ef4aaea03ed87ace0910315bc5945405b9c4bedfa4f075"
      define_method(:install) do
        bin.install "cirrus"
        generate_completions_from_executable(bin/"cirrus", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
