# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orchard < Formula
  desc "Orchestrator for running Tart Virtual Machines on a cluster of Apple Silicon devices"
  homepage "https://github.com/cirruslabs/orchard"
  version "0.54.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cirruslabs/orchard/releases/download/0.54.0/orchard-darwin-amd64.tar.gz"
      sha256 "9ffecc944856ef0d4c60aaa2df353de815d922940b308968cf21a5824e78a844"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cirruslabs/orchard/releases/download/0.54.0/orchard-darwin-arm64.tar.gz"
      sha256 "de744b9fede23a197b90caf8e14eff793d762203f47722455685793b3e341940"

      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/orchard/releases/download/0.54.0/orchard-linux-amd64.tar.gz"
      sha256 "7a901d06dcfe1652a16838a8bf45b2fad8b1dffbad84cc85f69517e53cfb128a"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cirruslabs/orchard/releases/download/0.54.0/orchard-linux-arm64.tar.gz"
      sha256 "f67d39342e915a2d50092ab83ae7db78ed76c7a3dfb38e336b2d85dd45a4cfae"
      define_method(:install) do
        bin.install "orchard"
        generate_completions_from_executable(bin/"orchard", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      See the Github repository for more information
    EOS
  end
end
